from __future__ import annotations

TOPIC_KEYWORDS: dict[str, set[str]] = {
    "gaming": {
        "game",
        "games",
        "gaming",
        "play",
        "playing",
        "steam",
        "xbox",
        "playstation",
        "nintendo",
        "switch",
        "fps",
        "rpg",
        "fortnite",
        "minecraft",
        "valorant",
        "league",
        "dota",
        "csgo",
        "cs2",
        "elden",
        "zelda",
        "mario",
        "pokemon",
        "gta",
        "esports",
        "raid",
        "boss",
        "dungeon",
        "loot",
        "console",
        "pc",
        "gpu",
        "ping",
    },
    "food": {
        "food",
        "cook",
        "cooking",
        "recipe",
        "restaurant",
        "pizza",
        "sushi",
        "burger",
        "taco",
        "pasta",
        "ramen",
        "vegan",
        "breakfast",
        "lunch",
        "dinner",
        "snack",
        "coffee",
        "tea",
        "beer",
        "wine",
        "dessert",
        "cake",
        "hungry",
        "spicy",
    },
    "music": {
        "song",
        "songs",
        "music",
        "album",
        "band",
        "guitar",
        "piano",
        "drums",
        "spotify",
        "playlist",
        "concert",
        "singer",
        "rapper",
        "rap",
        "rock",
        "metal",
        "jazz",
        "edm",
        "pop",
        "vinyl",
    },
    "tech": {
        "code",
        "coding",
        "python",
        "javascript",
        "typescript",
        "rust",
        "server",
        "api",
        "debug",
        "deploy",
        "git",
        "github",
        "docker",
        "linux",
        "database",
        "sql",
        "react",
        "node",
        "ai",
        "llm",
        "model",
        "software",
        "hardware",
        "cpu",
        "cloud",
        "compiler",
        "bug",
        "feature",
        "refactor",
    },
    "work": {
        "job",
        "career",
        "salary",
        "interview",
        "boss",
        "promotion",
        "hire",
        "coworker",
        "office",
        "remote",
        "meeting",
        "deadline",
        "project",
        "manager",
        "resume",
        "company",
        "business",
    },
    "location": {
        "live",
        "lives",
        "living",
        "moved",
        "moving",
        "city",
        "country",
        "state",
        "town",
        "home",
        "rent",
        "travel",
        "trip",
        "vacation",
        "flight",
        "hotel",
        "visit",
        "born",
        "hometown",
    },
    "health": {
        "doctor",
        "hospital",
        "health",
        "exercise",
        "workout",
        "gym",
        "diet",
        "sleep",
        "anxiety",
        "depression",
        "therapy",
        "medication",
        "sick",
        "pain",
        "injury",
        "fitness",
        "yoga",
        "mental",
    },
    "social": {
        "friend",
        "friends",
        "relationship",
        "dating",
        "boyfriend",
        "girlfriend",
        "partner",
        "wife",
        "husband",
        "married",
        "family",
        "parent",
        "brother",
        "sister",
        "child",
        "kids",
        "wedding",
    },
    "creative": {
        "art",
        "artist",
        "draw",
        "drawing",
        "paint",
        "painting",
        "write",
        "writing",
        "writer",
        "story",
        "film",
        "photo",
        "photography",
        "design",
        "graphic",
        "animation",
        "creative",
        "portfolio",
    },
    "sports": {
        "football",
        "basketball",
        "soccer",
        "baseball",
        "hockey",
        "tennis",
        "golf",
        "nba",
        "nfl",
        "team",
        "season",
        "playoffs",
        "coach",
        "athlete",
        "score",
        "goal",
        "olympics",
        "ufc",
        "mma",
    },
    "pets": {
        "dog",
        "dogs",
        "cat",
        "cats",
        "pet",
        "pets",
        "puppy",
        "kitten",
        "vet",
        "breed",
        "adopt",
        "rescue",
        "walk",
        "treat",
        "fish",
        "bird",
        "parrot",
        "hamster",
        "rabbit",
        "turtle",
    },
    "media": {
        "movie",
        "movies",
        "show",
        "shows",
        "series",
        "anime",
        "manga",
        "book",
        "books",
        "reading",
        "watch",
        "watched",
        "netflix",
        "hulu",
        "youtube",
        "podcast",
        "episode",
        "season",
        "trailer",
    },
    "education": {
        "school",
        "college",
        "university",
        "degree",
        "major",
        "class",
        "study",
        "student",
        "teacher",
        "professor",
        "exam",
        "homework",
        "lecture",
        "grade",
        "gpa",
        "graduation",
        "thesis",
    },
    "finance": {
        "money",
        "invest",
        "investing",
        "stock",
        "stocks",
        "crypto",
        "bitcoin",
        "budget",
        "saving",
        "savings",
        "debt",
        "loan",
        "mortgage",
        "credit",
        "bank",
        "tax",
        "income",
        "expense",
        "retirement",
        "market",
        "price",
        "cost",
    },
}


def _normalize(text: str) -> str:
    return " ".join((text or "").strip().lower().split())


def detect_topic(text: str) -> str:
    if not text:
        return "general"
    tokens = set(_normalize(text).split())
    if not tokens:
        return "general"
    best_topic = "general"
    best_hits = 0
    for topic, keywords in TOPIC_KEYWORDS.items():
        hits = len(tokens & keywords)
        if hits > best_hits:
            best_hits = hits
            best_topic = topic
    return best_topic if best_hits >= 1 else "general"
